sidekiq background jobs
HASNAT204/Ecommerce-Project pull request #13
Opened 2023-08-03 14:34 UTC by HASNAT204

2023-08-04 07:01 UTC, sajidali-dnt requested changes

2023-08-04 07:01 UTC, sajidali-dnt commented on spec/mailers/previews/seller_mailer_preview.rb
why is this file present? are you going to write test cases?

2023-08-04 14:00 UTC, HASNAT204 commented on app/jobs/send_seller_email_job.rb
> +    order.order_items.each do |order_item|
ok

2023-08-04 14:01 UTC, HASNAT204 commented on spec/mailers/previews/seller_mailer_preview.rb
it was created by default when generating mailer and now i have removed it.

2023-08-04 14:02 UTC, HASNAT204 commented on app/controllers/orders_controller.rb
> +    return if current_user.has_role("Buyer")
yes this issue is now fixed.

2023-08-07 06:34 UTC, sajidali-dnt approved these changes

2023-08-07 06:35 UTC, merged