Authorization
HASNAT204/Ecommerce-Project pull request #5
Opened 2023-07-13 14:51 UTC by HASNAT204

2023-07-14 06:46 UTC, sajidali-dnt requested changes

2023-07-14 06:46 UTC, sajidali-dnt commented on app/controllers/products_controller.rb
> +    @product.product_images.destroy_all
will this line delete images from storage?

2023-07-14 06:46 UTC, sajidali-dnt commented on app/controllers/products_controller.rb
> +    @product.save
why did you call save here?

2023-07-14 06:46 UTC, sajidali-dnt commented on app/models/product_image.rb
> +  has_one_attached :image
can we not add images directly without the ProductImage model?

2023-07-14 11:28 UTC, HASNAT204 commented on app/models/product_image.rb
> +  has_one_attached :image
yes we can add images directly but i followed db schema for it.

2023-07-14 11:31 UTC, HASNAT204 commented on app/controllers/products_controller.rb
> +    @product.save
i should delete it its unnecessary destroy method will automatically call save changes.

2023-07-17 07:40 UTC, sajidali-dnt approved these changes

2023-07-17 07:41 UTC, sajidali-dnt requested changes

2023-07-17 07:41 UTC, sajidali-dnt commented on app/controllers/products_controller.rb
> +    @product.product_images.destroy_all
resolve this issue

2023-07-18 05:51 UTC, sajidali-dnt requested changes

2023-07-18 05:51 UTC, sajidali-dnt commented on app/controllers/products_controller.rb
>      if @product.update(product_params)
why are you calling @product.update method here? You have called @product.save method as well.

2023-07-18 05:51 UTC, sajidali-dnt commented on app/models/user.rb
> +  has_many :cart_items,dependent: :destroy
add space before dependent

2023-07-18 06:20 UTC, HASNAT204 commented on app/models/user.rb
> +  has_many :cart_items,dependent: :destroy
Done

2023-07-18 06:22 UTC, HASNAT204 commented on app/controllers/products_controller.rb
>      if @product.update(product_params)
i have called @product.save method because i was calling assign images method after update now i have fixed it.

2023-07-19 07:11 UTC, sajidali-dnt requested changes

2023-07-19 07:11 UTC, sajidali-dnt commented on app/controllers/cart_items_controller.rb
>      product = Product.find(params[:product_id])
make a private method for this

2023-07-19 07:11 UTC, sajidali-dnt commented on app/controllers/cart_items_controller.rb
>      if product.user == current_user
fix indentation problem

2023-07-19 08:33 UTC, sajidali-dnt requested changes

2023-07-19 08:33 UTC, sajidali-dnt commented on app/controllers/products_controller.rb
> +   @product.product_images.destroy_all
fix indentation issue

2023-07-19 09:01 UTC, sajidali-dnt approved these changes

2023-07-19 09:02 UTC, merged